### ISSUE TITLE
Duplicate sources in nomDB

### ISSUE THREAD

**Issue by mduong7** [MapofLife/vernacular-names#100]
Several species have multiple sources, (Eg. EOL source for the same common name entered 3 times). Would be great to have this cleaned up so that we don't have repeating information.

**Comment by gaurav** [comment]
This would be a great first step to fixing #40.

**Comment by gaurav** [comment]
I think I've deleted all the duplicates with the same source name. I'll close this issue after I add a test to check for this problem returning -- which it will, once we've consolidated sources somewhat.
