### ISSUE TITLE
Error in bulk adding names

### ISSUE THREAD

**Issue by ljvillanueva** [MapofLife/vernacular-names#106]
When adding ~100 species, ran the "Fill from EOL" button, but when submitted, got this error:

```
Error: server returned error 400: {"error":["syntax error at end of input"]}
```

**Comment by gaurav** [comment]
I think I've figured it out: this error is triggered when you hit "Upload names" on the bulk upload page without adding any new names or updating existing names. I'll push a change that fixes it now, which will close this bug, but please reopen it if that doesn't squish it!
