### ISSUE TITLE
Red kangaroo is now called a Blue File?

### ISSUE THREAD

**Issue by funkycoda** [MapofLife/vernacular-names#118]
This is completely wrong.
![redkangaroo](https://cloud.githubusercontent.com/assets/1484128/9151198/542329fe-3dc8-11e5-959a-c310863e7a4c.png)

**Comment by ljvillanueva** [comment]
Fixed, but will keep this open while tracking why that name appeared in taxonomy_translations.

**Comment by ljvillanueva** [comment]
Now the name chosen is by priority and by number of sources that have it.
