### ISSUE TITLE
/import text input should be as wide as possible

### ISSUE THREAD

**Issue by gaurav** [MapofLife/vernacular-names#83]
The text fields in /import can be quite wide, so this table should be as wide as possible so we can see as much of each vernacular name as possible. I'm not sure why it's not, but if it's an easy fix, could you please fix it? Otherwise, assign it back to me and I'll have a look when I have a moment.

**Comment by funkycoda** [comment]
This should be simple. It'll be applied across the app.

**Comment by funkycoda** [comment]
If happy with 75aea76eda164198563222786bc1b912b72c8c18, go ahead and close this.

**Comment by gaurav** [comment]
This looks great -- thanks so much!
