### ISSUE TITLE
Sources: amphibians and reptiles

### ISSUE THREAD

**Issue by gaurav** [MapofLife/vernacular-names#9]
- [ ] Scientific and Common Names
of the Reptiles and Amphibians of North America by Ellin Beltz, 2006: http://ebeltz.net/herps/etymain.html (North America only)
- [ ] Complete Guide to Scientific and Common Names of Reptiles and Amphibians of the World by Frank and Ramus, 1996: http://www.amazon.com/Complete-Scientific-Common-Reptiles-Amphibians/dp/0964103230

**Comment by mduong7** [comment]
Source used for North American herps: SOCIETY FOR THE STUDY OF AMPHIBIANS AND REPTILES

Complete Guide (Frank and Ramus) looks like it's an outdated resource with some strange common names.
