### ISSUE TITLE
Sort by priority and date

### ISSUE THREAD

**Issue by ljvillanueva** [MapofLife/vernacular-names#94]
Some names were clashing because they had the same priority and the top one was decided by the database. For taxonomy_translations I'm sorting by both priority and date of the row, would be good to have the same solution here:

```
...  ORDER BY vernacular_names.source_priority DESC, vernacular_names.created_at DESC LIMIT 1...
```

This is the script I'm using to get taxonomy_translations:
https://github.com/MapofLife/database/blob/master/scripts_autopopulate/taxonomy_translations.py

**Comment by gaurav** [comment]
This is how NomDB does it as well, as of https://github.com/MapofLife/vernacular-names/commit/30fcfcee761ec1596899fb830006c24893d3ebbf#diff-9ef2f7a05e4f52d1764deef30a6a59c5R79 -- closing!
