### ISSUE TITLE
Have report on names with weird characters

### ISSUE THREAD

**Issue by ljvillanueva** [MapofLife/vernacular-names#99]
*Cathorops steindachneri* has among the several options 
```
Steindachner&#39;s sea catfish
```
I don't think any code is expecting the names formatted in this way, and probably will not translate to the correct display.

Perhaps an automated fix for some of these cases and/or a page with these cases for spot checks?

**Comment by gaurav** [comment]
Definitely! I'm hoping to eventually write a regular expression search (#42) which should be able to help with this.
